---
title: "Analiza kriminala i socio-ekonomskih faktora"
author:
- "Jan Grgić"
- "Bernard Spiegl"
- "Korina Šimičević"
- "Dunja Šmigovec"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Uvod

## Učitavanje paketa

```{r echo=T, error=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
```

## Učitavanje podataka

```{r}
chicago_year = read.csv('data/Crimes_-_One_year_prior_to_present.csv')
chicago_pc = read.csv('data/Chicago_poverty_and_crime.csv')
dim(chicago_pc)
dim(chicago_year)
```

## Učitavanje podataka o vremenu

```{r}
#vadi listu datuma
dates <- strptime(c(chicago_year$DATE..OF.OCCURRENCE), format="%m/%d/%Y %H:%M:%S %p", tz="America/Chicago")

#vadi listu sati
hours <- as.numeric(format(strptime(chicago_year$DATE..OF.OCCURRENCE, format="%m/%d/%Y %I:%M:%S %p", tz="America/Chicago"), format="%H"))
table(hours)
```

## Podaci o učestalosti kriminala ovisno o dobu dana

```{r}
hist(hours + 1, breaks = 0:24, main="Učestalost kriminala ovisno o dobu dana", xlab="Sat u danu", ylab="Frekvencija", col="light blue", xaxt='n')
axis(side=1, at=seq(0,24), labels=seq(0,24))
```

## Usporedba učestalosti krađa s učestalosti kriminala vezanih uz narkotike

```{r}
```

## Veze između socio-ekonomskih faktora i kategorije kriminala

```{r}
```